#!/bin/bash

# Pull the latest changes from Git
sudo git pull

# NOTE: To add directories to syncable list use following command format
# sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/ /var/www/html/INSERT_YOUR_NEW_DIRECTORY_HERE/

# Sync the staging directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/ /var/www/html/sargents_sweets/

# Sync the hw05 directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/hw05/ /var/www/html/hw05/

# Sync the hw06 directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/hw06/ /var/www/html/hw06/

# Sync the hw07 directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/hw07/ /var/www/html/hw07/

# Sync the hw08 directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/hw08/ /var/www/html/hw08/

# Sync the in_class directory to the web directory (in class assignment)
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/in_class/ /var/www/html/in_class/

# Sync the puzzle directory to the web directory (in class assignment)
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/puzzle/ /var/www/html/puzzle/

# Sync the hw12 directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/hw12/ /var/www/html/hw12/

# Sync the hw13 directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/hw13/ /var/www/html/hw13/

# Sync the hw14 directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/hw14/ /var/www/html/hw14/

# Sync the hw14 directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/hw15/ /var/www/html/hw15/

# Sync the hw14 directory to the web directory
sudo rsync -av --delete /home/ubuntu/staging/aws_assigned_server/hw16/ /var/www/html/hw16/

# Reload the Nginx service to apply changes
sudo service nginx reload
